<?php
/**
 * @file
 * Module for IDS IMS integration with Solr search
 */

/**
 * Alter Solr documents before they are sent to Solr for indexing.
 *
 * @param array $documents
 *   An array of SearchApiSolrDocument objects ready to be indexed, generated
 *   from $items array.
 * @param SearchApiIndex $index
 *   The search index for which items are being indexed.
 * @param array $items
 *   An array of items being indexed.
 */
function idsims_solr_search_api_solr_documents_alter(array &$documents, SearchApiIndex $index, array $items) {

	$sites_terms = _ids_main_get_all_site_terms();
	$language_terms = _ids_main_get_all_language_terms();

	$server = $index->server();
	$server_machine_name = $server->machine_name;
	$server_site_machine_name_arr = explode('_', $server_machine_name);
	$server_site_machine_name = $server_site_machine_name_arr[0];

	foreach ($documents as $document_key => $document) {
		$index_id_arr = $document->getField('index_id');
		$index_id = $index_id_arr['value'];
		$item_id_arr = $document->getField('item_id');
		if($index_id == 'openapi_index_taxonomy'){
			$taxonomy_term = taxonomy_term_load($item_id_arr['value']);
			if($taxonomy_term){
				/* Index TAXONOMY TERMS */
				$vocabulary_machine_name = $taxonomy_term->vocabulary_machine_name;
				/* Object ID (object_id) */
				$field_language = _idsims_main_field_language($vocabulary_machine_name, $taxonomy_term, 'field_site_ref');
				if(!isset($taxonomy_term->field_object_id[$field_language])){
					drupal_set_message('NO object ID set for :' . $taxonomy_term->name);
				}
				$document->setField('object_id', $taxonomy_term->field_object_id[$field_language][0]['value']);
				/* Title (title_field) */
				$document->setField('title', $taxonomy_term->name);
				/* Site (taken from taxonomy vocabulary machine name e.g. ids_bridge_themes) */
				$vocabulary_machine_name_arr = explode('_', $vocabulary_machine_name);
				$site_machine_name = $vocabulary_machine_name_arr[1];
				/*Object type -- remove plural */
				$object_type = (isset($vocabulary_machine_name_arr[2])) ? substr($vocabulary_machine_name_arr[2], 0, -1):$vocabulary_machine_name_arr[1];
				if($site_machine_name == 'countries'){
					$site_machine_name = $server_site_machine_name;
					$object_type = 'country';
				}
				$document->setField('site', $site_machine_name);
				$document->setField('object_type', $object_type);
				/* Asset ID (asset_id) */
				$category_id = substr($taxonomy_term->field_object_id[$field_language][0]['value'], 1);/*remove 'C' at front of category ID */
				$document->setField('category_id', $category_id);
				/* Category path (category_path) */
				$document->setField('category_path', _idsims_main_get_term_path($taxonomy_term->tid));
				/* Category term level */
				$level = _idsims_main_get_term_depth($taxonomy_term->tid);
				$document->setField('cat_level', $level);
				/* Parent array */
				$parent_tids = array();
				_idsims_main_get_parent_tid_array($parent_tids, $taxonomy_term->tid);
				$category_objects = array();
				foreach($parent_tids as $parent_tid){
					$category_object = _idsims_solr_build_category_object_arr($parent_tid, $term = FALSE, $object_type);
					if($category_object){
						$category_objects[] = $category_object;
					}
				}
				if(count($category_objects)){
					$xmlString = _idsims_solr_build_list_object_array_field('parent', $category_objects);
					$document->setField('parent_object_array', $xmlString);
				}
				/* First Parent / Super Parent (vocabulary ID) */
				if(count($parent_tids)){
					$document->setField('cat_first_parent', _idsims_main_get_numeric_asset_id('taxonomy_term', $parent_tids[0]));
					$document->setField('cat_parent', _idsims_main_get_numeric_asset_id('taxonomy_term', $parent_tids[count($parent_tids)-1]));
				} else {
					$document->setField('cat_first_parent', $category_id);
					$document->setField('cat_parent', $taxonomy_term->vid);
				}
				$document->setField('cat_superparent', $taxonomy_term->vid);
				/* Child array */
				$child_tids = _idsims_main_get_child_tid_array($taxonomy_term->tid);
				$category_objects = array();
				foreach($child_tids as $child_tid){
					$category_object = _idsims_solr_build_category_object_arr($child_tid, $term = FALSE, $object_type);
					if($category_object){
						$category_objects[] = $category_object;
					}
				}
				if(count($category_objects)){
					$xmlString = _idsims_solr_build_list_object_array_field('child', $category_objects);
					$document->setField('children_object_array', $xmlString);
				}
				
				/* We need to write the timestamp out explicitly even though Drupal adds it anyway
				 * as it needs to be in this format for the API or it errors
				 */
				$timestamp_now = date("Y-m-d\Th:i:s\Z");
				$document->setField('timestamp', $timestamp_now);
				
			}
		} else {
			/* Index NODES */
			$node = node_load($item_id_arr['value']);
			if($node){
				$field_language = _idsims_main_field_language($node->type, $node, 'field_site_ref');
				$site_term_tid = $node->field_site_ref[$field_language][0]['tid'];
				$site_term = taxonomy_term_load($site_term_tid);

				/* Object ID (object_id) */
				$document->setField('object_id', $node->field_object_id[$field_language][0]['value']);

				/* Object type */
				$object_type = 'Document';
				if($node->type == 'ids_organisation'){
					$object_type = 'Organisation';
				}
				$document->setField('object_type', $object_type);

				/* Asset ID (asset_id) */
				$assetid = substr($node->field_object_id[$field_language][0]['value'], 1);/*remove 'A' at front of asset ID */
				$document->setField('asset_id', $assetid);

				/* Author (author) */
				foreach($node->field_authors[$field_language] as $author_item){
					$author_term = taxonomy_term_load($author_item['tid']);
					$document->addField('author', $author_term->name);
				}

				/* Site (site_ref) */
				$site_ref_tid = $node->field_site_ref[$field_language][0]['tid'];
				$site_machine_name = $sites_terms[$site_ref_tid]->field_machine_name[LANGUAGE_NONE][0]['value'];
				$document->setField('site', $site_machine_name);

				/* Title (title_field) */
				$document->setField('title', $node->title_field[$field_language][0]['value']);

				/* Regions (field_SITE_regions) */
				_idsims_solr_build_category_fields($document, $node, 'region', $site_machine_name, $object_xml = FALSE);

				/* Subjects (field_SITE_subjects) */
				_idsims_solr_build_category_fields($document, $node, 'subject', $site_machine_name);

				/* Theme (field_SITE_themes) */
				_idsims_solr_build_category_fields($document, $node, 'theme', $site_machine_name);

				/* Set date created/updated */
				$timestamp = date("Y-m-d\Th:i:s\Z", $node->created);
				$document->setField('date_created', $timestamp);
				$timestamp = date("Y-m-d\Th:i:s\Z", $node->changed);
				$document->setField('date_updated', $timestamp);
				
				/* We need to write the timestamp out explicitly even though Drupal adds it anyway
				 * as it needs to be in this format for the API or it errors
				 */
				$timestamp_now = date("Y-m-d\Th:i:s\Z");
				$document->setField('timestamp', $timestamp_now);
				
				/* Description/Abstract */
				$document->setField('description', $node->body[$field_language][0]['value']);

				/* Document medium (change to an array? Keeping inline with old API which is single value string) */
				foreach($node->field_media[$field_language] as $document_medium_item){
					$document_medium_term = taxonomy_term_load($document_medium_item['tid']);
					$document->addField('document_medium', $document_medium_term->name);
					break;
				}
		
				/* Document types */
				foreach($node->field_document_medium[$field_language] as $document_medium_item){
					$document_medium_term = taxonomy_term_load($document_medium_item['tid']);
					$document->addField('document_medium', $document_medium_term->name);
				}
				
				/* Et al. */
				if(isset($node->field_et_al[$field_language][0]['value'])){
					$et_al_value = ($node->field_et_al[$field_language][0]['value']) ? 'true':'false';
					$document->setField('et_al', $et_al_value);
				}
				
				/* Headline */
				if(isset($node->field_headline[$field_language][0]['value'])){
					$document->setField('headline', $node->field_headline[$field_language][0]['value']);
				}
				
				/* Keyword */
				foreach($node->field_tags[$field_language] as $keyword_item){
					$keyword_term = taxonomy_term_load($keyword_item['tid']);
					$document->addField('keyword', $keyword_term->name);
				}
				
				/* Collections */
				foreach($node->field_collections[$field_language] as $collection_item){
					$collection_term = taxonomy_term_load($collection_item['tid']);
					$document->addField('collection', $collection_term->name);
				}
				
				/* Translations */
				/* Language ID */
				if(isset($node->translations->data)){
					$lang_list_objects = array();
					foreach($node->translations->data as $lang_iso_code => $translation_data){
						$oryx_lang_id = _idsims_solr_iso_code_to_ids_api_lang_id_for_drupal($lang_iso_code);
						$document->addField('language_id', $oryx_lang_id);
						$lang_list_object = array();
						$lang_list_object['isocode'] = $lang_iso_code;
						if(isset($node->title_field[$lang_iso_code][0]['value'])){
							$lang_list_object['title'] = htmlspecialchars($node->title_field[$lang_iso_code][0]['value']);
						}
						if(isset($node->body[$lang_iso_code][0]['value'])){
							$lang_list_object['description'] = htmlspecialchars($node->body[$lang_iso_code][0]['value']);
						}
						if(isset($node->field_headline[$lang_iso_code][0]['value'])){
							$lang_list_object['headline'] = htmlspecialchars($node->field_headline[$lang_iso_code][0]['value']);
						}
						$lang_list_object['language_id'] = $oryx_lang_id;
						$lang_list_objects[] = $lang_list_object;
					}
				}
				/* Language Array */
				if(count($lang_list_objects)){
					$xmlString = _idsims_solr_build_list_object_array_field('language', $lang_list_objects);
					$document->setField('language_array', $xmlString);
				}
				
				/* Language Name (change to an array using $node->translations above? Keeping inline with old API which is single value string) */
				if(isset($language_terms[$node->language]->name)){
					$document->setField('language_name', $language_terms[$node->language]->name);
				} else {
					drupal_set_message('Language not set for node(' . $node->id . ') asset ID:' . $assetid);
				}
				
				/* Website URL */
				$website_url = '';
				if($site_machine_name == 'bridge'){
					$website_url = 'http://www.bridge.ids.ac.uk/go/display&amp;type=' . $object_type . '&amp;id=' . $assetid;
				}
				if($site_machine_name == 'eldis'){
					$website_url = 'http://www.eldis.org/go/display&type=' . $object_type . '&id=' . $assetid;
				}
				if($website_url){
					$document->setField('website_url', $website_url);
				}
				
				/* Licence Type */
				foreach($node->field_licence_type_term[$field_language] as $licence_type_item){
					$licence_type_term = taxonomy_term_load($licence_type_item['tid']);
					$document->addField('licence_type', $licence_type_term->name);
					break;
				}
				
			}
		}
	}

}

/*
 * Build the category object array
 */
function _idsims_solr_build_category_object_arr($tid = FALSE, $term = FALSE, $category_ref){
	if(!$term){
		if(!$tid){
			return FALSE;
		}
		$term = taxonomy_term_load($tid);
	}
	$category_object = array();
	if(isset($term->field_object_id[LANGUAGE_NONE][0]['value'])){
		$category_object_id = $term->field_object_id[LANGUAGE_NONE][0]['value'];
		$category_object['object_id'] = $category_object_id;
		$category_object['object_type'] = $category_ref;
	} else {
		return FALSE;
	}
	$category_object['object_name'] = $term->name;
	$category_object['level'] = _idsims_main_get_term_depth($term->tid);
	if(isset($term->field_archived[LANGUAGE_NONE][0]['value'])){
		$category_object['archived'] = ($term->field_archived[LANGUAGE_NONE][0]['value']) ? 'true':'false';
	}
	return $category_object;
}

/*
 * Build the fields for categories. Regions, Themes, Subjects
 */
function _idsims_solr_build_category_fields(&$document, $node, $category_ref, $site_machine_name, $object_xml = TRUE){
	$category_ref_field = 'field_' . $site_machine_name . '_' . $category_ref . 's';
	$category_objects = array();
	foreach($node->{$category_ref_field}[LANGUAGE_NONE] as $term_ref_item){
		$term = taxonomy_term_load($term_ref_item['tid']);
		$category_object = _idsims_solr_build_category_object_arr(FALSE, $term, $category_ref);
		if(isset($term->field_object_id[LANGUAGE_NONE][0]['value'])){
			$category_object_id = $term->field_object_id[LANGUAGE_NONE][0]['value'];
			$document->addField('category_' . $category_ref . '_ids', $category_object_id);
		}
		$document->addField('category_' . $category_ref . '_path', _idsims_main_get_term_path($term->tid));
		$category_object_output = _idsims_solr_build_list_object_output($category_object, $category_ref, $object_xml);
		$document->addField('category_' . $category_ref . '_objects', $category_object_output);
		if($category_object){
			$category_objects[] = $category_object;
		}
	}
	if(count($category_objects)){
		$xmlString = _idsims_solr_build_list_object_array_field($category_ref, $category_objects);
		$document->setField('category_' . $category_ref . '_array', $xmlString);
	}
}

/*
 * Builds object array fields
 */
function _idsims_solr_build_list_object_array_field($list_ref, $list_objects){
	$xmlString = '<' . $list_ref . 'List>';
	foreach($list_objects as $list_object){
		$xmlString .= _idsims_solr_build_list_object_output($list_object, $list_ref);
	}
	$xmlString .= '</' . $list_ref . 'List>';
	return $xmlString;
}

/*
 * Builds object fields
 */
function _idsims_solr_build_list_object_output($list_object, $list_ref, $object_xml = TRUE){
	$outputString = '';
	foreach($list_object as $key => $value){
		if($object_xml){
			$outputString .= '<' . $key . '>';
			$outputString .= $value;
			$outputString .= '</' . $key . '>';
		} else {
			if($outputString){
				$outputString .= '|';
			}
			$outputString .= $value;
		}
	}
	if($object_xml){
		if($outputString){
			$outputString = '<' . $list_ref . '>' . $outputString .  '</' . $list_ref . '>';
		}
	}
	return $outputString;
}

/*
 * Get Old Oryx language ID from ISO code
 * Needs review ... do we need to preserve this ID?
 * What is it used for?
 */
function _idsims_solr_iso_code_to_ids_api_lang_id_for_drupal($lang_iso_code){
	$lang_code_arr = _idsims_main_get_oryx_id_iso_lang_arr();
	$lang_code_arr = array_flip($lang_code_arr);
	if(isset($lang_code_arr[$lang_iso_code])){
		return $lang_code_arr[$lang_iso_code];
	}
	return FALSE;
}

