<?php
/**
 * @file
 * Module for IDS IMS integration with Solr search
 */

/**
 * Alter Solr documents before they are sent to Solr for indexing.
 *
 * @param array $documents
 *   An array of SearchApiSolrDocument objects ready to be indexed, generated
 *   from $items array.
 * @param SearchApiIndex $index
 *   The search index for which items are being indexed.
 * @param array $items
 *   An array of items being indexed.
 */
function idsims_solr_search_api_solr_documents_alter(array &$documents, SearchApiIndex $index, array $items) {
	
	$sites_terms = _ids_main_get_all_site_terms();
	
	$server = $index->server();
	$server_machine_name = $server->machine_name;
	$server_site_machine_name_arr = explode('_', $server_machine_name);
	$server_site_machine_name = $server_site_machine_name_arr[0];
	
	foreach ($documents as $document_key => $document) {
		$index_id_arr = $document->getField('index_id');
		$index_id = $index_id_arr['value'];
		$item_id_arr = $document->getField('item_id');
		if($index_id == 'openapi_index_taxonomy'){
			$taxonomy_term = taxonomy_term_load($item_id_arr['value']);
			if($taxonomy_term){			
				/* Index TAXONOMY TERMS */
				$vocabulary_machine_name = $taxonomy_term->vocabulary_machine_name;
				/* Object ID (object_id) */
				$field_language = _idsims_main_field_language($vocabulary_machine_name, $taxonomy_term, 'field_site_ref');
				if(!isset($taxonomy_term->field_object_id[$field_language])){
					drupal_set_message('NO object ID set for :' . $taxonomy_term->name);
				}
				$document->setField('object_id', $taxonomy_term->field_object_id[$field_language][0]['value']);
				/* Title (title_field) */
				$document->setField('title', $taxonomy_term->name);
				/* Site (taken from taxonomy vocabulary machine name e.g. ids_bridge_themes) */
				$vocabulary_machine_name_arr = explode('_', $vocabulary_machine_name);
				$site_machine_name = $vocabulary_machine_name_arr[1];
				/*Object type -- remove plural */
				$object_type = (isset($vocabulary_machine_name_arr[2])) ? substr($vocabulary_machine_name_arr[2], 0, -1):$vocabulary_machine_name_arr[1];
				if($site_machine_name == 'countries'){
					$site_machine_name = $server_site_machine_name;
					$object_type = 'country';
				}
				$document->setField('site', $site_machine_name);
				$document->setField('object_type', $object_type);
				/* Asset ID (asset_id) */
				$category_id = substr($taxonomy_term->field_object_id[$field_language][0]['value'], 1);/*remove 'C' at front of category ID */
				$document->setField('category_id', $category_id);
				/* Category path (category_path) */
				$document->addField('category_path', _idsims_main_get_term_path($taxonomy_term->tid));
				/* Category term level */
				$level = _idsims_main_get_term_depth($taxonomy_term->tid);
				$document->addField('cat_level', $level);
				/* Parent array */
				$parent_tids = array();
				_idsims_main_get_parent_tid_array($parent_tids, $taxonomy_term->tid);
				$category_objects = array();
				foreach($parent_tids as $parent_tid){
					$category_object = _idsims_solr_build_category_object_arr($parent_tid, $term = FALSE, $object_type);
					if($category_object){
						$category_objects[] = $category_object;
					}
				}
				if(count($category_objects)){
					$xmlString = _idsims_solr_build_category_array_field('parent', $category_objects);
					$document->addField('parent_object_array', $xmlString);
				}
				/* First Parent / Super Parent (vocabulary ID) */
				if(count($parent_tids)){
					$document->addField('cat_first_parent', _idsims_main_get_numeric_asset_id('taxonomy_term', $parent_tids[0]));
					$document->addField('cat_parent', _idsims_main_get_numeric_asset_id('taxonomy_term', $parent_tids[count($parent_tids)-1]));
				} else {
					$document->addField('cat_first_parent', $category_id);
					$document->addField('cat_parent', $taxonomy_term->vid);
				}
				$document->addField('cat_superparent', $taxonomy_term->vid);
				/* Child array */
				$child_tids = _idsims_main_get_child_tid_array($taxonomy_term->tid);
				$category_objects = array();
				foreach($child_tids as $child_tid){
					$category_object = _idsims_solr_build_category_object_arr($child_tid, $term = FALSE, $object_type);
					if($category_object){
						$category_objects[] = $category_object;
					}
				}
				if(count($category_objects)){
					$xmlString = _idsims_solr_build_category_array_field('child', $category_objects);
					$document->addField('children_object_array', $xmlString);
				}
			}
		} else {
			/* Index NODES */
			$node = node_load($item_id_arr['value']);
			if($node){
				$field_language = _idsims_main_field_language($node->type, $node, 'field_site_ref');
				$site_term_tid = $node->field_site_ref[$field_language][0]['tid'];
				$site_term = taxonomy_term_load($site_term_tid);
	
				/* Object ID (object_id) */
				$document->setField('object_id', $node->field_object_id[$field_language][0]['value']);
	
				/* Asset ID (asset_id) */
				$assetid = substr($node->field_object_id[$field_language][0]['value'], 1);/*remove 'A' at front of asset ID */
				$document->setField('asset_id', $assetid);
	
				/* Author (author) */
				foreach($node->field_authors[$field_language] as $author_item){
					$author_term = taxonomy_term_load($author_item['tid']);
					$document->addField('author', $author_term->name);
				}
	
				/* Site (site_ref) */
				$site_ref_tid = $node->field_site_ref[$field_language][0]['tid'];
				$site_machine_name = $sites_terms[$site_ref_tid]->field_machine_name[LANGUAGE_NONE][0]['value'];
				$document->setField('site', $site_machine_name);
				
				/* Title (title_field) */
				$document->setField('title', $node->title_field[$field_language][0]['value']);
				
				/* Regions (field_SITE_regions) */
				_idsims_solr_build_category_fields($document, $node, 'region', $site_machine_name, $object_xml = FALSE);
				
				/* Subjects (field_SITE_subjects) */
				_idsims_solr_build_category_fields($document, $node, 'subject', $site_machine_name);
				
				/* Theme (field_SITE_themes) */
				_idsims_solr_build_category_fields($document, $node, 'theme', $site_machine_name);
			}
		}
	}
	
}

/*
 * Build the category object array
 */
function _idsims_solr_build_category_object_arr($tid = FALSE, $term = FALSE, $category_ref){
	if(!$term){
		if(!$tid){
			return FALSE;
		}
		$term = taxonomy_term_load($tid);
	}
	$category_object = array();
	if(isset($term->field_object_id[LANGUAGE_NONE][0]['value'])){
		$category_object_id = $term->field_object_id[LANGUAGE_NONE][0]['value'];
		$category_object['object_id'] = $category_object_id;
		$category_object['object_type'] = $category_ref;
	} else {
		return FALSE;
	}
	$category_object['object_name'] = $term->name;
	$category_object['level'] = _idsims_main_get_term_depth($term->tid);
	if(isset($term->field_archived[LANGUAGE_NONE][0]['value'])){
		$category_object['archived'] = ($term->field_archived[LANGUAGE_NONE][0]['value']) ? 'true':'false';
	}
	return $category_object;
}

/*
 * Build the fields for categories. Regions, Themes, Subjects
 */
function _idsims_solr_build_category_fields(&$document, $node, $category_ref, $site_machine_name, $object_xml = TRUE){
	$category_ref_field = 'field_' . $site_machine_name . '_' . $category_ref . 's'; 
	$category_objects = array();
	foreach($node->{$category_ref_field}[LANGUAGE_NONE] as $term_ref_item){
		$term = taxonomy_term_load($term_ref_item['tid']);
		$category_object = _idsims_solr_build_category_object_arr(FALSE, $term, $category_ref);
		if(isset($term->field_object_id[LANGUAGE_NONE][0]['value'])){
			$category_object_id = $term->field_object_id[LANGUAGE_NONE][0]['value'];
			$document->addField('category_' . $category_ref . '_ids', $category_object_id);
		}
		$document->addField('category_' . $category_ref . '_path', _idsims_main_get_term_path($term->tid));
		$category_object_output = _idsims_solr_build_category_object_output($category_object, $category_ref, $object_xml);
		$document->addField('category_' . $category_ref . '_objects', $category_object_output);
		if($category_object){
			$category_objects[] = $category_object;
		}
	}	
	if(count($category_objects)){
		$xmlString = _idsims_solr_build_category_array_field($category_ref, $category_objects);
		$document->addField('category_' . $category_ref . '_array', $xmlString);
	}
}

function _idsims_solr_build_category_array_field($category_ref, $category_objects){
	$xmlString = '<' . $category_ref . 'List>';
	foreach($category_objects as $category_object){
		$xmlString .= _idsims_solr_build_category_object_output($category_object, $category_ref);
	}
	$xmlString .= '</' . $category_ref . 'List>';
	return $xmlString;
}

function _idsims_solr_build_category_object_output($category_object, $category_ref, $object_xml = TRUE){
	$outputString = '';
	foreach($category_object as $key => $value){
		if($object_xml){
			$outputString .= '<' . $key . '>';
			$outputString .= $value;
			$outputString .= '</' . $key . '>';
		} else {
			if($outputString){
				$outputString .= '|';
			}
			$outputString .= $value;
		}
	}	
	if($object_xml){
		if($outputString){
			$outputString = '<' . $category_ref . '>' . $outputString .  '</' . $category_ref . '>';
		}
	}
	return $outputString;
}


