<?php
/**
 * @file
 * Module for bespoke IDS IMS customisations
 */

/*
 * Constants for import term IDs etc
 */

define('IDSIMS_COLLECTIONS_VOC_NAME', 'ids_collections');
define('IDSIMS_AUTHORS_VOC_NAME', 'ids_authors');

define('IDSIMS_BRIDGE_ORGANISATION_ID', 2921);

/*
 * Subject IDs
 */
define('IDSIMS_BRIDGE_ORG_LINK_BIBLIO_SID', 1798);
define('IDSIMS_BRIDGE_ORG_LINK_BRIEF_SID', 1797);
define('IDSIMS_BRIDGE_ORG_LINK_REPORT_SID', 1796);

define('IDSIMS_FLAG_ABSTRACT_SID', 1900);
define('IDSIMS_FLAG_SENTINEL_OUTPUT_SID', 1952);
define('IDSIMS_FLAG_RECOMMENDED_READING_SID', 12);

define('IDSIMS_COLLECTION_UPDATES_NAME', 'Updates');
define('IDSIMS_COLLECTION_UPDATES_SID', 1800);
define('IDSIMS_COLLECTION_UPDATES_2007_SID', 1806);
define('IDSIMS_COLLECTION_UPDATES_2008_SID', 1805);
define('IDSIMS_COLLECTION_UPDATES_2009_SID', 1804);
define('IDSIMS_COLLECTION_UPDATES_2010_SID', 1803);
define('IDSIMS_COLLECTION_UPDATES_2011_SID', 1801);
define('IDSIMS_COLLECTION_UPDATES_2012_SID', 1858);
define('IDSIMS_COLLECTION_UPDATES_2013_SID', 1895);
define('IDSIMS_COLLECTION_UPDATES_2014_SID', 1998);

define('IDSIMS_FUNDER_PARENT_SID', 1842);
define('IDSIMS_CONTENT_PARTNER_PARENT_SID', 1957);

define('IDSIMS_IDS_ELDIS_SUBJECTS_VOC_ID', 15);
define('IDSIMS_IDS_BRIDGE_SUBJECTS_VOC_ID', 16);
define('IDSIMS_IDS_COLLECTIONS_VOC_ID', 24);


define('IDSIMS_ORYX_EXTRAS_XML_URL', 'http://romeo.eldis.org/ORYX-extras/');

/*
 * Site term ids
 */
define('IDSIMS_SITE_ELDIS_TID', 96624);
define('IDSIMS_SITE_BRIDGE_TID', 96625);

/**
 * Implement hook_menu()
 */
function idsims_import_menu() {
	$items['admin/config/ids-ims/import-settings'] = array(
    'title' => 'Import settings',
    'description' => 'General Import settings',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_settings_form'),
	);
	$items['admin/config/ids-ims/import-extras'] = array(
    'title' => 'Documents: Import additional fields from old IMS',
    'description' => 'Import any additional fields required for Documents from the old Oyrx DB provided by custom XML feed',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_import_extras_form'),
	);
	$items['admin/config/ids-ims/import-extras-api'] = array(
    'title' => 'Documents: Import additional fields from API',
    'description' => 'Import any additional fields required for Documents from the IDS API - Translations',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_import_extras_api_form'),
	);
	$items['admin/config/ids-ims/import-extras-orgs'] = array(
    'title' => 'Organisations: Import additional fields from old IMS',
    'description' => 'Import any additional fields required for Organisations from the old Oyrx DB provided by custom XML feed',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_import_extras_orgs_form'),
	);
	$items['admin/config/ids-ims/post-process'] = array(
    'title' => 'Documents: Post proccessing on imported Oryx data',
    'description' => 'Moving imported data into a more appropriate structure from shared fields due to limitations of Oryx system',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_import_post_process_form'),
	);
	$items['admin/config/ids-ims/post-process-taxonomy'] = array(
    'title' => 'Documents: Post proccessing on taxonomy reference fields.',
    'description' => 'Updating taxonomy reference fields where Terms have been moved to another vocabulary (IDS Collections) in Taxonomy Manager',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_import_post_process_taxonomy_reference_form'),
	);
	$items['admin/config/ids-ims/post-process-orgs'] = array(
    'title' => 'Organisations: Post proccessing on imported Oryx data',
    'description' => 'Moving imported data into a more appropriate structure from shared fields due to limitations of Oryx system',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_import_post_process_orgs_form'),
	);
	$items['admin/config/ids-ims/amalgamate-orgs'] = array(
    'title' => 'Organisations Amalgamate!',
    'description' => 'Find any BRIDGE copies of Organisations merge them into The Eldis version and delete.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_import_amalgamate_orgs_form'),
	);
	$items['admin/config/ids-ims/import-countries-regions'] = array(
    'title' => 'Import Countries to Regions data',
    'description' => 'Countries to Regions data',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_country_regions_form'),
	);
	$items['admin/config/ids-ims/import-term-descriptions'] = array(
    'title' => 'Import Term Descriptions',
    'description' => 'Get the desction data for terms from the API',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idsims_import_term_descriptions_form'),
	);
	return $items;
}


/**
 * Build a form for general Import settings
 */
function idsims_import_settings_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Set what is done/ignored on import</h2>');
    $form['idsims_import_do_set_mime_types'] = array(
    '#title' => t('Set mime types for full text documents on import'),
    '#type' => 'select',
    '#options' => array(
    0 => 'No',
    1 => 'Yes',
    ),
    '#required' => TRUE,
    '#default_value' => variable_get('idsims_import_do_set_mime_types', 0),
    '#description' => t('Only if this is set to Yes will full text document mimetype information be set in the IDS Document URL Entity'),
    );
    $form['idsims_import_do_set_cover_thumb_image'] = array(
    '#title' => t('Set cover thumbnail image for full text documents on import'),
    '#type' => 'select',
    '#options' => array(
    0 => 'No',
    1 => 'Yes',
    ),
    '#required' => TRUE,
    '#default_value' => variable_get('idsims_import_do_set_cover_thumb_image', 0),
    '#description' => t('Only if this is set to Yes will the cover thumbnail image be set in the IDS Document URL Entity (NOTE only works if mime type is set too!)'),
    );
    return system_settings_form($form);
}

/**
 * Build a form for Import Extras settings
 */
function idsims_import_import_extras_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Documents: Extra data pulled from the old system via a bespoke XML feed ('.l('e.g.', IDSIMS_ORYX_EXTRAS_XML_URL . '?xml=true&aid=56240').')</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>Publication uncertain date</li>'
    . '<li>SUBJECTS: Content partners from subjects array made node reference to Organisation</li>'
    . '<li>SUBJECTS: Funders from subjects array made node reference to Organisation</li>'
    . '<li>SUBJECTS: Flags applied to documents (Abstract, Sentinel Output, Recommended Reading)</li>'
    . '<li>SECTORS: Process Updates (as a Collection)</li>'
    . '<li>SECTORS: Process BRIDGE Bibliography, Briefing or Report</li>'
    . '<li>SECTORS: Process remaining Sectors as Document Types</li>'
    . '<li>USERS: Apply User ID for document creator</li>'
    . '</ul>',
    );
    $form['start_offset'] = array(
    '#title' => t('Start offset'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('Grab nodes from...'), 
    '#default_value' => 0,   
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Import'),
    );
    return $form;
}



/**
 * Build a form for Import Extras API settings
 */
function idsims_import_import_extras_api_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Documents: Extra data pulled from the IDS API ('.l('e.g.','http://api.ids.ac.uk/openapi/bridge/get/documents/A53212/full').')</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>Translations from language_array: Title, Description (abstract), headline</li>'
    . '</ul>',
    );
    $form['start_offset'] = array(
    '#title' => t('Start offset'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('Grab nodes from...'), 
    '#default_value' => 0,   
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Import'),
    );
    return $form;
}

/**
 * Build a form for Import Extras Organisations settings
 */
function idsims_import_import_extras_orgs_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Organisations: Extra data pulled from the old system via a bespoke XML feed ('.l('e.g.', IDSIMS_ORYX_EXTRAS_XML_URL . '?xml=true&aid=56240').')</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>Has Hosting Permission</li>'
    . '<li>Has Redistribute Permission</li>'
    . '<li>Has Permission to host information</li>'
    . '<li>Licence Type</li>'
    . '</ul>',
    );
    $form['start_offset'] = array(
    '#title' => t('Start offset'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('Grab nodes from...'), 
    '#default_value' => 0,   
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Import'),
    );
    return $form;
}

/**
 * Build a form for Import post process
 */
function idsims_import_import_post_process_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Manipulating the data that has been pulled into Drupal</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>From the Pubisher ID field populate Publisers field which is a node reference to Organisations</li>'
    . '<li>Update Site taxonomy reference from field_site</li>'
    . '<li>Move external url field into new Document URL entity</li>'
    . '</ul>',
    );
    $form['start_offset'] = array(
    '#title' => t('Start offset'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('Grab nodes from...'), 
    '#default_value' => 0,   
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Post Process'),
    );
    return $form;
}

/**
 * Build a form for Taxonomy Reference update
 */
function idsims_import_import_post_process_taxonomy_reference_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Updating taxonomy reference fields</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>Updating taxonomy reference fields where they have been moved using Taxonomy Manager</li>'
    . '</ul>',
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Taxonomy Reference update'),
    );
    return $form;
}

/**
 * Build a form for Import post process (Organisations)
 */
function idsims_import_import_post_process_orgs_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Manipulating the data that has been pulled into Drupal</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>Update Site taxonomy reference from field_site</li>'
    . '</ul>',
    );
    $form['start_offset'] = array(
    '#title' => t('Start offset'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('Grab nodes from...'), 
    '#default_value' => 0,   
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Post Process'),
    );
    return $form;
}

/**
 * Build a form for Import of term descriptions
 */
function idsims_import_term_descriptions_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Get more taxonomy data from API</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>Term descriptions</li>'
    . '</ul>',
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Term update'),
    );
    return $form;
}

/**
 * Build a form for Import post process amalgamation of Organisations
 */
function idsims_import_import_amalgamate_orgs_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['intro_text'] = array(
    '#markup' => '<h2>Amalgamation of Organisations</h2>'
    . '<p>Process tasks:</p>'
    . '<ul>'
    . '<li>Find any BRIDGE copies of Organisations merge them into The Eldis version and delete.</li>'
    . '</ul>',
    );
    $form['import_limit'] = array(
    '#title' => t('Import limit'),
    '#type'  => 'textfield',
    '#size' => 10,
    '#description' => t('The number of items to import. If left blank then all'), 
    '#default_value' => 5,   
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Amalgamation!'),
    );
    return $form;
}

function _idsims_import_set_batch_jobs($batch_name, $batch_id, &$form, &$form_state, $asset_type_id = 'ids_document', $field_conditions = FALSE){
	variable_set('idsims_import_batch_process_running', 1);
	$import_limit = $form_state['values']['import_limit'];
        $start_offset = (isset($form_state['values']['start_offset'])) ? $form_state['values']['start_offset']:0;

	$batch = array(
    'title' => t($batch_name . ' ...'),
    'operations' => array(),
    'init_message' => t('Commencing'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('An error occurred during processing'),
    'finished' => 'idsims_import_' . $batch_id . '_finished',
	);

	$query = new EntityFieldQuery();

	if(is_array($asset_type_id)){
		$asset_type_operator = 'IN';
	} else {
		$asset_type_operator = '=';
	}
	$query->entityCondition('entity_type', 'node')
	->entityCondition('bundle', $asset_type_id, $asset_type_operator)
	->propertyCondition('status', NODE_PUBLISHED)
	->addMetaData('account', user_load(1)); // Run the query as user 1.
        
        if(is_array($field_conditions)){
            foreach($field_conditions as $field_condition){
               $query->fieldCondition($field_condition->field_name, $field_condition->column_name, $field_condition->value, $field_condition->operator); 
            }
        }

	if($import_limit){
		$query->range($start_offset,$import_limit);
	}

	$result = $query->execute();

	if (!empty($result['node'])) {
		$nids = array_keys($result['node']);
		foreach ($nids as $nid) {
			$batch['operations'][] = array('_idsims_import_process_' . $batch_id, array($nid));
		}
	}

	batch_set($batch);
}

function idsims_import_import_extras_form_submit(&$form, &$form_state) {
        $field_condition = new stdClass();
        $field_condition->field_name = 'field_build_xml_complete';
        $field_condition->column_name = 'value';
        $field_condition->value = 1;
        $field_condition->operator = '!=';
        $field_conditions = array($field_condition);
	_idsims_import_set_batch_jobs('Importing Extra fields', 'import_extras', $form, $form_state, 'ids_document', $field_conditions);
}

function idsims_import_import_extras_api_form_submit(&$form, &$form_state) {
	_idsims_import_set_batch_jobs('Importing Extra fields API', 'import_extras_api', $form, $form_state, array('ids_document', 'ids_organisation'));
}

function idsims_import_import_extras_orgs_form_submit(&$form, &$form_state) {
        $field_condition = new stdClass();
        $field_condition->field_name = 'field_build_xml_complete';
        $field_condition->column_name = 'value';
        $field_condition->value = 1;
        $field_condition->operator = '!=';
        $field_conditions = array($field_condition);
	_idsims_import_set_batch_jobs('Importing Extra fields for organisations', 'import_extras_orgs', $form, $form_state, 'ids_organisation', $field_conditions);
}

function idsims_import_import_post_process_form_submit(&$form, &$form_state) {
	_idsims_import_set_batch_jobs('Import data post process', 'import_post_process', $form, $form_state);
}

function idsims_import_import_post_process_taxonomy_reference_form_submit(&$form, &$form_state) {
	_idsims_import_set_batch_jobs('Import data post process', 'import_post_process_taxonomy_reference', $form, $form_state, array('ids_document', 'ids_organisation'));
}

function idsims_import_import_post_process_orgs_form_submit(&$form, &$form_state) {
	_idsims_import_set_batch_jobs('Import data post process', 'import_post_process', $form, $form_state, 'ids_organisation');
}

function idsims_import_import_amalgamate_orgs_form_submit(&$form, &$form_state) {
	_idsims_import_set_batch_jobs('Import data post process', 'import_amalgamate_orgs', $form, $form_state, 'ids_organisation');
}

function idsims_import_term_descriptions_form_submit(&$form, &$form_state) {
	$batch_id = 'term_extras';
	
	$import_limit = $form_state['values']['import_limit'];

	$batch = array(
    'title' => t('Term Extras ...'),
    'operations' => array(),
    'init_message' => t('Commencing'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('An error occurred during processing'),
    'finished' => 'idsims_import_' . $batch_id . '_finished',
	);

        $taxonomies = array('ids_bridge_regions', 'ids_bridge_subjects', 'ids_bridge_themes', 'ids_eldis_regions', 'ids_eldis_subjects', 'ids_eldis_themes', 'ids_countries');
        
        foreach($taxonomies as $taxonomy_id){
        
            $query = new EntityFieldQuery();

            $query->entityCondition('entity_type', 'taxonomy_term')
            ->entityCondition('bundle', $taxonomy_id, '=')
            ->addMetaData('account', user_load(1)); // Run the query as user 1.

            if($import_limit){
                    $limit = (int) ($import_limit/count($taxonomies));
                    $query->range(0, $limit);
            }

            $result = $query->execute();

            if (!empty($result['taxonomy_term'])) {
                    $tids = array_keys($result['taxonomy_term']);
                    foreach ($tids as $tid) {
                            $batch['operations'][] = array('_idsims_import_process_' . $batch_id, array($tid, $taxonomy_id));
                    }
            }
            
        }

	batch_set($batch);
}



function _idsims_import_sectors_to_doc_type(&$node, $cat_assetid, $cat_assetid_raw, $cat_name){
	$oryx_doc_types_arr = array();
	$oryx_doc_types_arr[1] = 'Background/overview document';
	$oryx_doc_types_arr[2] = 'Bibliography';
	$oryx_doc_types_arr[3] = 'Book';
	$oryx_doc_types_arr[4] = 'Book chapter';
	$oryx_doc_types_arr[5] = 'Case studies';
	$oryx_doc_types_arr[6] = 'Conference paper';
	$oryx_doc_types_arr[7] = 'Country profile';
	$oryx_doc_types_arr[8] = 'Good practice guide';
	$oryx_doc_types_arr[9] = 'Grey literature';
	$oryx_doc_types_arr[10] = 'Journal article';
	$oryx_doc_types_arr[11] = 'Journal issue';
	$oryx_doc_types_arr[12] = 'Literature review';
	$oryx_doc_types_arr[13] = 'Manual/toolkit';
	$oryx_doc_types_arr[14] = 'Not known';
	$oryx_doc_types_arr[15] = 'Other';
	$oryx_doc_types_arr[16] = 'Policy briefing';
	$oryx_doc_types_arr[17] = 'Policy document';
	$oryx_doc_types_arr[18] = 'Presentation';
	$oryx_doc_types_arr[19] = 'Research report (or study)';
	$oryx_doc_types_arr[20] = 'Working paper (includes discussion paper)';

	$bridge_sector_doc_types_arr = array();
	$bridge_sector_doc_types_arr['Background Document'] = 1;
	$bridge_sector_doc_types_arr['Bibliography'] = 2;
	$bridge_sector_doc_types_arr['BRIDGE Bibliography'] = 2;
	$bridge_sector_doc_types_arr['Briefing'] = 1;
	$bridge_sector_doc_types_arr['BRIDGE Briefing'] = 16;
	$bridge_sector_doc_types_arr['Case Study'] = 5;
	$bridge_sector_doc_types_arr['Cutting Edge Pack'] = 'GROUPING';
	$bridge_sector_doc_types_arr['Fundraising'] = 'GROUPING';
	$bridge_sector_doc_types_arr['Gender Country Profile'] = 7;
	$bridge_sector_doc_types_arr['Good Practice Guide'] = 8;
	$bridge_sector_doc_types_arr['Manual / Toolkit'] = 13;
	$bridge_sector_doc_types_arr['Policy / Planning'] = 'GROUPING';
	$bridge_sector_doc_types_arr['Report'] = 0; //Do NOTHING
	$bridge_sector_doc_types_arr['BRIDGE Report'] = 19;
	$bridge_sector_doc_types_arr['Research Output'] = 19;
	$bridge_sector_doc_types_arr['Thematic Overview'] = 1;

	$doc_type_term_name = NULL;
	$oryx_doc_type_id = NULL;
	if(isset($bridge_sector_doc_types_arr[$cat_name])){
		$oryx_doc_type_id = $bridge_sector_doc_types_arr[$cat_name];
		$doc_type_term_name = isset($oryx_doc_types_arr[$oryx_doc_type_id]) ? $oryx_doc_types_arr[$oryx_doc_type_id]:NULL;
	}
	if($doc_type_term_name){
		$terms = taxonomy_get_term_by_name($doc_type_term_name, $vocabulary = 'ids_document_type');
		foreach($terms as $term){
			$tid = $term->tid;
			_idsims_main_apply_term_to_entity_field($node, 'document_types', $tid);
		}
	}

	if($oryx_doc_type_id == 'GROUPING'){
		/* first chek the grouping term exists. If not create */
		$terms = taxonomy_get_term_by_name($cat_name, $vocabulary = IDSIMS_COLLECTIONS_VOC_NAME);
		$tid = NULL;
		$vid = get_collections_taxonomy_vid();
		if(!count($terms)){
			/* If IDS collection term doesn't exist. Then create it */
			drupal_set_message('Creating IDS Collection: ' . $cat_name);
			$tid = _idsims_main_create_taxonomy_term($cat_name, $vid);
		} else {
			foreach($terms as $term){
				$tid = $term->tid;
			}
		}
		if($tid){
			_idsims_main_apply_term_to_entity_field($node, 'collections', $tid);
		}
	}

}

function _idsims_import_updates_collection(&$node, $cat_assetid, $cat_name){
	$cat_assetid_raw = substr($cat_assetid, 1);/*remove 'C' at front of asset ID */
	$update_arr = array(IDSIMS_COLLECTION_UPDATES_SID,
	IDSIMS_COLLECTION_UPDATES_2007_SID,
	IDSIMS_COLLECTION_UPDATES_2008_SID,
	IDSIMS_COLLECTION_UPDATES_2009_SID,
	IDSIMS_COLLECTION_UPDATES_2010_SID,
	IDSIMS_COLLECTION_UPDATES_2011_SID,
	IDSIMS_COLLECTION_UPDATES_2012_SID,
	IDSIMS_COLLECTION_UPDATES_2013_SID,
	IDSIMS_COLLECTION_UPDATES_2014_SID);
	if(in_array($cat_assetid_raw, $update_arr)){
		/* first chek the root update term exists. If not create */
		$terms = taxonomy_get_term_by_name(IDSIMS_COLLECTION_UPDATES_NAME, $vocabulary = IDSIMS_COLLECTIONS_VOC_NAME);
		$tid = NULL;
		$vid = get_collections_taxonomy_vid();
		if(!count($terms)){
			/* If root update term doesn't exist. Then create it */
			$tid = _idsims_main_create_taxonomy_term(IDSIMS_COLLECTION_UPDATES_NAME, $vid);
			variable_set('idsims_updates_root_tid', $tid);
		}
		$updates_root_tid = variable_get('idsims_updates_root_tid', 0);
		/* if this isn't the root item then save it and add to the tree */
		if($cat_assetid_raw != IDSIMS_COLLECTION_UPDATES_SID){
			$tid = _idsims_main_create_taxonomy_term($cat_name, $vid, $parent_id = $updates_root_tid);
		}

		/* now we've saved the term we need to link it to our document node (if not already)*/
		_idsims_main_apply_term_to_entity_field($node, 'collections', $tid);
	}
}

function get_collections_taxonomy_vid(){
	$vid = variable_get('collections_taxonomy_vid', 0);
	if(!$vid){
		$vid = _idsims_main_get_vid_from_vocab_machine_name(IDSIMS_COLLECTIONS_VOC_NAME);
		variable_set('collections_taxonomy_vid', $vid);
	}
	return $vid;
}

function get_authors_taxonomy_vid(){
	$vid = variable_get('authors_taxonomy_vid', 0);
	if(!$vid){
		$vid = _idsims_main_get_vid_from_vocab_machine_name(IDSIMS_AUTHORS_VOC_NAME);
		variable_set('authors_taxonomy_vid', $vid);
	}
	return $vid;
}

function _idsims_import_category_asset_id_to_organisation_asset_id_from_matrix($cat_assetid){
	/*
	 * Joe - it's a shame bu no way to do this apart from hardcode - the titles don't match
	 */
	/*
	 * Content Parners
	 */
	$asset_id_matrix = array();
	$asset_id_matrix['C2018'] = 'A4701'; /* African Centre for Constructive Resolution of Disputes (ACCORD) */
	$asset_id_matrix['C1968'] = 'A3533'; /* African Centre for Technology */
	$asset_id_matrix['C1960'] = 'A7332'; /* African Population and Health Research Center */
	$asset_id_matrix['C2001'] = 'A7114'; /* Afrobarometer */
	$asset_id_matrix['C2040'] = 'A7099'; /* Aga Khan University */
	$asset_id_matrix['C2048'] = 'A56214'; /* Association for Womens Rights in Development (AWID) */
	$asset_id_matrix['C1985'] = 'A65046'; /* BRICS Policy Center */
	$asset_id_matrix['C2045'] = 'A4384'; /* Cambodian Institute for Cooperation and Peace */
	$asset_id_matrix['C2005'] = 'A63302'; /* Centre for Chinese Studies (CCS) */
	$asset_id_matrix['C2044'] = 'A7365'; /* Centre for Conflict Resolution (CCR) */
	$asset_id_matrix['C1967'] = 'A7961'; /* Centre for Excellence on Sustainable Development in the context of Climate Change */
	$asset_id_matrix['C1973'] = 'A67889'; /* Centre for Gender and Social Transformation */
	$asset_id_matrix['C2060'] = 'A64270'; /* Centre For Human Rights and Policy Studies (CHRIPS) */
	$asset_id_matrix['C2024'] = 'A61408'; /* Centre for People and Forests (RECOFTC) */
	$asset_id_matrix['C2032'] = 'A4305'; /* Centre for Policy Dialogue, Bangladesh (CPD) */
	//$asset_id_matrix['C1966'] = 'A4497'; /* @ ALAN SAYS REMOVE – HAS NO CONTENT Centre for Policy Research *
	//$asset_id_matrix['C2042'] = 'A65946'; /* @ ALAN SAYS INCORRECT – Doesn’t appear to have org record in database but is here.. http://www.nwu.ac.za/centre-excellence-nutrition-cen-potchefstroom-campus Centre of Excellence for Nutrition */
	$asset_id_matrix['C2018'] = 'A70318'; /* China Institute of International Studies (CIIS) */
	$asset_id_matrix['C2033'] = 'A63318'; /* Chinese Academy for Environmental Planning (CAEP) */
	$asset_id_matrix['C2002'] = 'A7183'; /* Collective for Social Science Research */
	$asset_id_matrix['C2051'] = 'A5770'; /* Curatio International Foundation (CIF) */
	$asset_id_matrix['C1983'] = 'A68769'; /* CUTS Centre for International Trade, Economics & Environment (CUTS CITEE) */
	$asset_id_matrix['C1984'] = 'A4669'; /* Economic Research Forum (ERF) */
	//$asset_id_matrix['C2023'] = 'A1686'; /* @ ALAN SAYS REMOVE – HAS NO CONTENT Energy and Resources Institute *
	$asset_id_matrix['C1969'] = 'A5837'; /* Energy Research Centre, University of Capetown */
	$asset_id_matrix['C2027'] = 'A3719'; /* EQUINET */
	$asset_id_matrix['C1999'] = 'A69688'; /* Ethiopian Public health Institute (EPHI) */
	$asset_id_matrix['C2038'] = 'A7985'; /* Feminist Africa */
	$asset_id_matrix['C2029'] = 'A7040'; /* Food, Agriculture and Natural Resource Policy Analysis Network (FANRPAN) */
	//$asset_id_matrix['C2000'] = 'xxx'; /* @ ALAN SAYS REMOVE – HAS NO CONTENT Haramaya University *
	$asset_id_matrix['C2052'] = 'A5024'; /* Health Economics & HIV/AIDS Research Division (HEARD) */
	$asset_id_matrix['C2039'] = 'A4857'; /* Health Systems Trust */
	$asset_id_matrix['C2006'] = 'A69390'; /* HIV/AIDS Knowledge Management Communication Capacity (KMCC) */
	$asset_id_matrix['C1961'] = 'A66631'; /* Igarape Institute */
	$asset_id_matrix['C2055'] = 'A4457'; /* Institute for Global Dialogue (IGD) */
	$asset_id_matrix['C2020'] = 'A6360'; /* Institute for Poverty, Land and Agrarian Studies (PLAAS) */
	$asset_id_matrix['C1962'] = 'A4871'; /* Institute for Security Studies */
	$asset_id_matrix['C2012'] = 'A4671'; /* Institute of Economic Growth (IEG) */
	$asset_id_matrix['C1964'] = 'A6377'; /* Institute of Peace and Conflict Studies */
	$asset_id_matrix['C2057'] = 'A72927'; /* Institute of South Asian Studies (ISAS) */
	$asset_id_matrix['C2041'] = 'A34465'; /* Integrated Research and Action for Development (IRADe) */
	$asset_id_matrix['C2022'] = 'A66891'; /* International Centre for Climate Change and Development (ICCCAD) */
	$asset_id_matrix['C2025'] = 'A33403'; /* International Centre for Diarrhoeal Disease Research (icddr,b) */
	$asset_id_matrix['C2013'] = 'A1316'; /* International Centre for Integrated Mountain Development (ICIMOD) */
	$asset_id_matrix['C1972'] = 'A1352'; /* International Water Management Institute */
	$asset_id_matrix['C2031'] = 'A70942'; /* ISET-Nepal */
	$asset_id_matrix['C2021'] = 'A4397'; /* Kenya Institute for Public Policy Research and Analysis (KIPPRA) */
	$asset_id_matrix['C2034'] = 'A71117'; /* Knowledge Partnership Programme (KPP) */
	$asset_id_matrix['C1965'] = 'A37013'; /* Kofi Annan International Peacekeeping Training Centre */
	$asset_id_matrix['C2004'] = 'A7119'; /* @ M S Swaminathan Research Foundation (MSSRF) */
	//$asset_id_matrix['C2019'] = 'xxx'; /* @ ALAN SAYS HAS NO ORG RECORD - Mekelle University */
	//$asset_id_matrix['C2053'] = 'xxx'; /* @ REMOVE – HAS NO CONTENT MRC/UVRI Uganda Research Unit on AIDS *
	$asset_id_matrix['C2043'] = 'A69042'; /* Nigeria Stability and Reconciliation Programme (NSRP) */
	$asset_id_matrix['C2030'] = 'A6985'; /* Observer Research Foundation (ORF) */
	$asset_id_matrix['C2017'] = 'A34071'; /* Open Society Initiative for Southern Africa (OSISA) */
	$asset_id_matrix['C2026'] = 'A71264'; /* Public Health Foundation of India (PHFI) */
	$asset_id_matrix['C1963'] = 'A6983'; /* Refugee Law Project */
	$asset_id_matrix['C1959'] = 'A5531'; /* Research and Information System for Developing Countries */
	$asset_id_matrix['C2037'] = 'A6346'; /* Social Research Center */
	$asset_id_matrix['C1958'] = 'A4459'; /* South African Institute of International Affairs */
	$asset_id_matrix['C2016'] = 'A70323'; /* Southern African Resource Watch (SARW) */
	$asset_id_matrix['C2061'] = 'A66149'; /* 3 possibles?? SPARC */
	$asset_id_matrix['C2003'] = 'A4350'; /* Sustainable Development Policy Institute */
	$asset_id_matrix['C2014'] = 'A4074'; /* Trade and Industrial Policy Strategies, South Africa (TIPS) */
	$asset_id_matrix['C2028'] = 'A70784'; /* UONGOZI Institute */
	$asset_id_matrix['C1987'] = 'A69190'; /* Urban LandMark */
	$asset_id_matrix['C1979'] = 'A68239'; /* West Africa Civil Society Institute (WACSI) */
	$asset_id_matrix['C2036'] = 'A5691'; /* Women for Women’s Human Rights – New Ways */
	$asset_id_matrix['C1970'] = 'A1348'; /* World Agroforestry Centre */

	/*
	 * Funders
	 */
	$asset_id_matrix['C1834'] = 'A56922'; /* CDKN */
	
	/*
	 * Sevices
	 */
	$asset_id_matrix['C1878'] = 'A59314'; /* APCOM */
	$asset_id_matrix['C1815'] = 'A61093'; /* CSDMS */
	$asset_id_matrix['C1790'] = 'A32790'; /* DNet */
	$asset_id_matrix['C1905'] = 'A65311'; /* Evidence on Demand */
	$asset_id_matrix['C1867'] = 'A31035'; /* FAC */
	$asset_id_matrix['C1883'] = 'A63489'; /* FBFI */
	$asset_id_matrix['C2050'] = 'A6247'; /* GSDRC */
	$asset_id_matrix['C1846'] = 'A7686'; /* HDRC */
	$asset_id_matrix['C1946'] = 'A63060'; /* HEART */
	$asset_id_matrix['C2056'] = 'A72848'; /* Ideas to Impact */
	$asset_id_matrix['C1868'] = 'A59436'; /* IID */
	$asset_id_matrix['C1948'] = 'A66570'; /* LANSA */
	$asset_id_matrix['C1981'] = 'A68930'; /* Making All Voices Count */
	$asset_id_matrix['C1989'] = 'A58708'; /* 3ie */
	$asset_id_matrix['C2063'] = 'A64967'; /* APAN */
	$asset_id_matrix['C1994'] = 'A2921'; /* BRIDGE */
	$asset_id_matrix['C1990'] = 'A31711'; /* CCCCC */
	$asset_id_matrix['C1896'] = 'A61421'; /* ELLA/PALA */
	$asset_id_matrix['C1991'] = 'A4210'; /* IGIDR */
	$asset_id_matrix['C2062'] = 'A75055'; /* K-Developedia */
	$asset_id_matrix['C1996'] = 'A75054'; /* ObservAction */
	$asset_id_matrix['C1995'] = 'A75056'; /* OpenDocs */
	$asset_id_matrix['C1992'] = 'A3160'; /* PIDS SERP-P */
	$asset_id_matrix['C1997'] = 'A75100'; /* Sendesal (now Anacaonas) */
	$asset_id_matrix['C1882'] = 'A62277'; /* SoulBeat */
	$asset_id_matrix['C1993'] = 'A6071'; /* SPREP */
	$asset_id_matrix['C1897'] = 'A59959'; /* PIP */
	$asset_id_matrix['C1898'] = 'A6360'; /* PLAAS */
	$asset_id_matrix['C1947'] = 'A66149'; /* SPARC Nigeria */
	$asset_id_matrix['C1949'] = 'A65945'; /* Transform Nutrition */

	return (isset($asset_id_matrix[$cat_assetid])) ? $asset_id_matrix[$cat_assetid] : FALSE;
}

/**
 * Process an taxonomy_term asset
 */
function _idsims_import_process_term_extras($tid, $taxonomy_id, &$context) {
        $taxonomy_id_arr = explode('_', $taxonomy_id);
        $category_id = $taxonomy_id_arr[count($taxonomy_id_arr) - 1];
        $term = taxonomy_term_load($tid);
        if(isset($term->field_site[LANGUAGE_NONE][0]['value'])){
            $siteid = $term->field_site[LANGUAGE_NONE][0]['value'];
        } else {
            $siteid = 'eldis';
        }	
	$xml_feed_path_root = 'http://api.ids.ac.uk/openapi/'.$siteid.'/get/' . $category_id . '/';
	$assetid = $term->field_object_id[LANGUAGE_NONE][0]['value'];
	$idsapi_api_key = variable_get('idsapi_api_key', '');
	if($idsapi_api_key){
		$xml_feed_path_full = $xml_feed_path_root . $assetid . '/full?_token_guid=' . $idsapi_api_key;
		$field_data = _idsims_import_idsapi_get_data($xml_feed_path_full);
		if($field_data){
			_idsims_import_process_import_extras_api_update_term($term, $field_data, $assetid);
			$context['message'] = t('Updating term %title : Asset ID = %assetid', array('%title' => $term->name, '%assetid' => $assetid));
		}
	} else {
		drupal_set_message('IDS API Key not set');
	}        
}

/**
 * Process an asset for extra fields import
 */
function _idsims_import_process_import_extras($nid, &$context) {
	$node = node_load($nid);
	$xml_feed_path_root = IDSIMS_ORYX_EXTRAS_XML_URL . '?xml=true&aid=';
	$assetid = $node->field_object_id[LANGUAGE_NONE][0]['value'];
	$raw_assetid = substr($assetid, 1);/*remove 'A' at front of asset ID */
	$xml_feed_path_full = $xml_feed_path_root . $raw_assetid;
	$field_data = idsims_import_get_endpoint_response($xml_feed_path_full);
	$field_data = _idsims_import_simpleXML2array($field_data);
	_idsims_import_process_import_extras_update_node($node, $field_data, $assetid);
	$context['message'] = t('Updating node %title : Asset ID = %assetid', array('%title' => $node->title, '%assetid' => $assetid));
}

/**
 * Process an asset for extra fields from API import
 */
function _idsims_import_process_import_extras_api($nid, $asset_type, &$context) {
	$node = node_load($nid);
	$siteid = $node->field_site[LANGUAGE_NONE][0]['value'];
        $asset_type = ($node->type == 'ids_document') ? 'documents':'organisations';
	$xml_feed_path_root = 'http://api.ids.ac.uk/openapi/'.$siteid.'/get/' . $asset_type . '/';
	$assetid = $node->field_object_id[LANGUAGE_NONE][0]['value'];
	$idsapi_api_key = variable_get('idsapi_api_key', '');
	if($idsapi_api_key){
		$xml_feed_path_full = $xml_feed_path_root . $assetid . '/full?_token_guid=' . $idsapi_api_key;
		$field_data = _idsims_import_idsapi_get_data($xml_feed_path_full);
		if($field_data){
			_idsims_import_process_import_extras_api_update_node($node, $field_data, $assetid);
			$context['message'] = t('Updating node %title : Asset ID = %assetid', array('%title' => $node->title, '%assetid' => $assetid));
		}
	} else {
		drupal_set_message('IDS API Key not set');
	}
}

// Call the IDS API URL.
function _idsims_import_idsapi_get_data($url) {
	$response = drupal_http_request($url);
	if (isset($response->data)) {
		$data = json_decode($response->data, true);
	}
	else {
		$message = 'The API call failed.';
		if (isset($response->code)) {
			$message .= ' Code: ' . $response->code;
		}
		drupal_set_message($message);
		$data = FALSE;
	}
	return $data;
}



/**
 * Process an asset for extra fields import oganisations
 */
function _idsims_import_process_import_extras_orgs($nid, &$context) {
	$node = node_load($nid);
	$xml_feed_path_root = IDSIMS_ORYX_EXTRAS_XML_URL . 'orgs.cfm?xml=true&aid=';
	$assetid = $node->field_object_id[LANGUAGE_NONE][0]['value'];
	$raw_assetid = substr($assetid, 1);/*remove 'A' at front of asset ID */
	$xml_feed_path_full = $xml_feed_path_root . $raw_assetid;
	$field_data = idsims_import_get_endpoint_response($xml_feed_path_full);
	$field_data = _idsims_import_simpleXML2array($field_data);
	_idsims_import_process_import_extras_update_organisation_node($node, $field_data, $assetid);
	$context['message'] = t('Updating node %title : Asset ID = %assetid', array('%title' => $node->title, '%assetid' => $assetid));
}


function _idsims_import_process_import_extras_update_organisation_node(&$node, &$field_data, $assetid) {
	/*
	 * First check we haven't already run this process
	 */
	if(isset($node->field_build_xml_complete[LANGUAGE_NONE][0]['value'])){
		if($node->field_build_xml_complete[LANGUAGE_NONE][0]['value']){
			/* We have already run this, exit */
			return;
		}
		/* Set the flag so we don't run again */
		$node->field_build_xml_complete[LANGUAGE_NONE][0]['value'] = 1;
	}	
	
	$node_updated = FALSE;

	/*
	 * Has Hosting Permission
	 */
	if(isset($field_data['has_hosting_permission'])){
		$node->field_has_hosting_copyright[LANGUAGE_NONE] = array();
		$cnt = 0;
		if($field_data['has_hosting_permission']){
			$node->field_has_hosting_copyright[LANGUAGE_NONE][$cnt]['value'] = 1;
		}
		$node_updated = TRUE;
	}

	/*
	 * Has Redistribute Permission
	 */
	if(isset($field_data['has_redistribute_permission'])){
		$node->field_has_redistribute_copyright[LANGUAGE_NONE] = array();
		$cnt = 0;
		if($field_data['has_redistribute_permission']){
			$node->field_has_redistribute_copyright[LANGUAGE_NONE][$cnt]['value'] = 1;
		}
		$node_updated = TRUE;
	}

	/*
	 * Has Permission to host information
	 */
	if(isset($field_data['permission_to_host_information'])){
		$node->field_permission_to_host_info[LANGUAGE_NONE] = array();
		$cnt = 0;
		if($field_data['permission_to_host_information']){
			$node->field_permission_to_host_info[LANGUAGE_NONE][$cnt]['value'] = $field_data['permission_to_host_information'];
		}
		$node_updated = TRUE;
	}
	//drupal_set_message('$field_data' . print_r($field_data, TRUE));
	/*
	* Licence Type
	*/
	if(isset($field_data['licence_type'])){
		foreach($field_data['licence_type'] as $key => $value){
			if($key == 'name'){
				$terms = taxonomy_get_term_by_name($value, $vocabulary = 'ids_licence_type');
				foreach($terms as $term){
					$tid = $term->tid;
					_idsims_main_apply_term_to_entity_field($node, 'licence_type_term', $tid);
				}
			}
		}
		$node_updated = TRUE;
	}

	if($node_updated){
		node_save($node);
	}
}


function _idsims_import_process_import_extras_update_node(&$node, &$field_data, $assetid) {
	/*
	 * First check we haven't already run this process
	 */
	if(isset($node->field_build_xml_complete[LANGUAGE_NONE][0]['value'])){
		if($node->field_build_xml_complete[LANGUAGE_NONE][0]['value']){
			/* We have already run this, exit */
			return;
		}
		/* Set the flag so we don't run again */
		$node->field_build_xml_complete[LANGUAGE_NONE][0]['value'] = 1;
	}
	
	/*
	 * Journal/Volume information
	 */
	if(isset($field_data['source_journal'])){
		$node->field_source_journal[LANGUAGE_NONE] = array();
		$node->field_source_journal[LANGUAGE_NONE][0]['value'] = $field_data['source_journal'];
	}
	if(isset($field_data['volume_part_in_series'])){
		$node->field_volume_part_in_series[LANGUAGE_NONE] = array();
		$node->field_volume_part_in_series[LANGUAGE_NONE][0]['value'] = $field_data['volume_part_in_series'];
	}
	if(isset($field_data['blds'])){
		$node->field_blds_record_number[LANGUAGE_NONE] = array();
		$node->field_blds_record_number[LANGUAGE_NONE][0]['value'] = $field_data['blds'];
	}	
	
	/*
	 * Publication date uncertain field
	 */
	$node_updated = FALSE;

	if(isset($field_data['publication_date_uncertain'])){
		$node->field_publication_date_uncertain[LANGUAGE_NONE] = array();
		$cnt = 0;
		foreach($field_data['publication_date_uncertain'] as $type => $value)
		{
			if($value){
				$node->field_publication_date_uncertain[LANGUAGE_NONE][$cnt]['value'] = $type;
				$cnt++;
			}
		}
		$node_updated = TRUE;
	}

	/*
	 * Apply Corperate Author
	 */
	if(isset($field_data['corporate_author']['name'])){
		$node->field_corporate_author_text[LANGUAGE_NONE] = array();
		$cnt = 0;
		if(is_array($field_data['corporate_author']['name'])){
			foreach($field_data['corporate_author']['name'] as $value){
				$node->field_corporate_author_text[LANGUAGE_NONE][$cnt]['value'] = $value;
				$cnt++;
			}
		} else {
			$node->field_corporate_author_text[LANGUAGE_NONE][$cnt]['value'] = $value;
		}
	}

	$site = isset($node->field_site[LANGUAGE_NONE][0]['value']) ? $node->field_site[LANGUAGE_NONE][0]['value']:'';
	/*
	 * process subjects (Eldis)
	 */
	if(isset($field_data['subjectList']) && $site == 'eldis'){
		_idsims_import_process_import_extras_update_node_subjects($node, $field_data['subjectList'], $assetid);
		$node_updated = TRUE;
	}

	/*
	 * process sectors (BRIDGE)
	 */
	if(isset($field_data['SectorList']) && $site == 'bridge'){
		_idsims_import_process_import_extras_update_node_sectors($node, $field_data['SectorList'], $assetid);
		$node_updated = TRUE;
	}

	/*
	 * Apply User ID for document creator
	 */
	if(isset($field_data['creator_id'])){
		$uid = _idsims_import_get_uid_from_creator_id($field_data['creator_id'], $assetid);
		if($uid){
			$node->uid = $uid;
			$node_updated = TRUE;
		}
	}

	if($node_updated){
		node_save($node);
	}
}

function _idsims_import_get_uid_from_creator_id($oryx_creator_id, $assetid){
	static $uid_to_creator_map;
	if(!is_array($uid_to_creator_map)){
		$uid_to_creator_map =  unserialize(variable_get('idsims_updates_uid_to_creator_map', 0));
		if(!is_array($uid_to_creator_map)){
			$uid_to_creator_map = array();
			$users = entity_load('user');
			foreach($users as $uid => $user_obj){
				if(isset($user_obj->field_oryx_user_id[LANGUAGE_NONE][0]['value'])){
					$cretor_id_arr = explode(',',trim($user_obj->field_oryx_user_id[LANGUAGE_NONE][0]['value']));
					foreach($cretor_id_arr as $creator_id){
						$uid_to_creator_map[$creator_id] = $uid;
					}
				}
			}
			variable_set('idsims_updates_uid_to_creator_map', serialize($uid_to_creator_map));
		}
	}
	if(isset($uid_to_creator_map[$oryx_creator_id])){
		return $uid_to_creator_map[$oryx_creator_id];
	} else {
		drupal_set_message('Warning:No User match on Asset:' . $assetid . ' for Oryx ID:'. $oryx_creator_id);
	}
	return FALSE;
}

function _idsims_import_ids_api_lang_id_to_iso_code_for_drupal($api_lang_id){
	$lang_code_arr = _idsims_main_get_oryx_id_iso_lang_arr();
	if(isset($lang_code_arr[$api_lang_id])){
		return $lang_code_arr[$api_lang_id];
	}
	return FALSE;
}

function _idsims_import_process_import_extras_api_update_term(&$term, &$field_data, $assetid) {
	$term_updated = FALSE;

	/*
	 * Description field
	 */
	if(isset($field_data['results']['description'])){
        drupal_set_message('NAME=' . $term->name . ' DESCRIPTION=' . $field_data['results']['description']);
		$term->description = $field_data['results']['description'];
		$term_updated = TRUE;
	} else {
		if($term->description == $term->name){
			/* the IDS IMS importer Drupal module just copied the name into the description for some reason, so let's just remove that */
			$term->description = '';
			$term_updated = TRUE;
		}
	}

	if($term_updated){
    	taxonomy_term_save($term);
	}
}

function _idsims_import_process_import_extras_api_update_node(&$node, &$field_data, $assetid) {
	/*
	 * First check we haven't already run this process
	 */
	if(isset($node->field_build_api_complete[LANGUAGE_NONE][0]['value'])){
		if($node->field_build_api_complete[LANGUAGE_NONE][0]['value']){
			/* We have already run this, exit */
			return;
		}
		/* Set the flag so we don't run again */
		$node->field_build_api_complete[LANGUAGE_NONE][0]['value'] = 1;
	}
	
	
	$node_updated = FALSE;

	/*
	 * Et al. field
	 */
	if(isset($field_data['results']['et_al'])){
		$et_al = ( $field_data['results']['et_al'] == 'false') ? 0:1;
		$node->field_et_al[LANGUAGE_NONE][0]['value'] = $et_al;
		$node->field_et_al[LANGUAGE_NONE][0]['safe_value'] = $et_al;
		$node_updated = TRUE;
	}
	
	/*
	 * Publication country
	 */
	if(isset($field_data['results']['publication_country_id'])){
		if($field_data['results']['publication_country_id']){
			$publication_country_id = 'A' . $field_data['results']['publication_country_id'];
			$country_tid = _idsims_main_get_items_from_asset_id($publication_country_id, 'taxonomy_term', 'ids_countries');
			if($country_tid){
				drupal_set_message('publication_country_id='.$publication_country_id . ' for Asset:' . $assetid);
				$node->field_country_of_publication[LANGUAGE_NONE] = array();
				$node->field_country_of_publication[LANGUAGE_NONE][0]['tid'] = $country_tid;
			}
		}
		$node_updated = TRUE;
	}
	
	/*
	 * Authors array
	 */
	$vid = get_authors_taxonomy_vid();
	if(isset($field_data['results']['author_array'])){
		foreach($field_data['results']['author_array'] as $author_item_arr){
			/* Delete and any field collections attached in another import (ideally there will only be one round, but whilst testing this is useful) */
			if(isset($node->field_authors_collection[LANGUAGE_NONE])){
				$collection_ids = array();
				foreach($node->field_authors_collection[LANGUAGE_NONE] as $delta => $value){
					$collection_ids[] = $value['value'];
				}
				entity_delete_multiple('field_collection_item', $collection_ids);
				$node->field_authors_collection[LANGUAGE_NONE] = array();
			}
			foreach($author_item_arr as $author_item){
				//drupal_set_message('data:' . print_r($author_item, true));
				$author_name = $author_item['first_name'] . ' ' . $author_item['last_name'];
				if(trim($author_name)){
					$is_editor = ($author_item['is_editor']) ? 1:0;
					$term_array = taxonomy_get_term_by_name($author_name); /* opptional $vid don't work?? */
					if(!count($term_array)){
						/* If IDS author term doesn't exist. Then create it */
						drupal_set_message('Creating IDS Author term: ' . $author_name);
						$term = new stdClass();
						$term->name = $author_name;
						$term->field_first_name[LANGUAGE_NONE][0] = array('value' => $author_item['first_name']);
						$term->field_last_name[LANGUAGE_NONE][0] = array('value' => $author_item['last_name']);
						$term->vid = $vid;
						$term->parent = array(0);
						taxonomy_term_save($term);
						$term_array = array();
						$term_array[$term->tid] = $term;
					}
	
					foreach($term_array as $term){
						//drupal_set_message('$term:' . print_r($term, true));
					  	// field collection items.
					  	
					    $field_collection_item = entity_create('field_collection_item', array('field_name' => 'field_authors_collection'));
					    $field_collection_item->setHostEntity('node', $node);
						$field_collection_item->field_author_ref[LANGUAGE_NONE][0]['target_id'] = $term->tid;
						$field_collection_item->field_author_ref[LANGUAGE_NONE][0]['entity'] = $term;
						$field_collection_item->field_author_ref[LANGUAGE_NONE][0]['access'] = 1;					    
					    $field_collection_item->field_is_editor[LANGUAGE_NONE][0] = array('value' => $is_editor);
					    $field_collection_item->save();
					    $node_updated = TRUE;
					    break; /* should only be one*/
					}
				}
			}
		}
	}

	/*
	 * Firstly we need to set the default language for this node and set the translatable field values
	 */
	$default_languge = LANGUAGE_NONE;
	if(isset($field_data['results']['language_id'][0])){
		/* For Documents */
		$lang_code = _idsims_import_ids_api_lang_id_to_iso_code_for_drupal($field_data['results']['language_id'][0]);
		if($lang_code){
			$default_languge = $lang_code;
			$node->language = $default_languge;
			/* Update Headline in the default language if set -- we didn't get headline on import */
			if(isset($field_data['results']['language_array']['language'])){
				foreach($field_data['results']['language_array']['language'] as $language_array){
					if($language_array['isocode']==$default_languge){
						if(isset($language_array['headline'])){
							$node->field_headline[LANGUAGE_NONE][0]['value'] = $language_array['headline'];
							$node->field_headline[$default_languge][0]['value'] = $language_array['headline'];
						}
					}
				}
			}
		} else {
			drupal_set_message('LOOKUP::'.print_r($field_data, TRUE) . '$lang_code:'.$lang_code);
		}
	}
	/* 
	 * For organistions 
	 * Let's default organisations to English
	 */
	if($node->type == 'ids_organisation'){
		$default_languge = 'en';
	}
	
	if($default_languge == LANGUAGE_NONE){
		drupal_set_message('Warning: No default language set for Node ID('.$node->nid.') Asset ID('.$assetid.')');
		drupal_set_message('$field_data:' . print_r($field_data, TRUE));
	} else {
		/* these two we know are in the default language just need to copy to lang specific field array */
		$node->title_field[$default_languge][0]['value'] = $node->title_field[LANGUAGE_NONE][0]['value'];
		$node->title_field[$default_languge][0]['safe_value'] = $node->title_field[LANGUAGE_NONE][0]['safe_value'];
		$node->body[$default_languge][0]['value'] = $node->body[LANGUAGE_NONE][0]['value'];
		$node->body[$default_languge][0]['safe_value'] = $node->body[LANGUAGE_NONE][0]['safe_value'];
		$node->body[$default_languge][0]['format'] = 'full_html';
		if(isset($node->field_alternative_name[LANGUAGE_NONE][0]['value'])){
			$node->field_alternative_name[$default_languge][0]['value'] = $node->field_alternative_name[LANGUAGE_NONE][0]['value'];
			$node->field_alternative_name[$default_languge][0]['safe_value'] = $node->field_alternative_name[LANGUAGE_NONE][0]['safe_value'];
		}
		/* Save the node in the Default language -- there should be no Language Neutral nodes */
		node_save($node);
	}
	
	
	/*
	 * Interigate language array to build translations
	 */
	if(isset($field_data['results']['language_array']['language'])){
		foreach($field_data['results']['language_array']['language'] as $language_array){
			//drupal_set_message('LANG::'.$language_array['isocode'].'::Asset::'.$assetid);
			if($language_array['isocode'] != $default_languge){
				if(function_exists('_idsims_main_save_entity_translation')){
					$field_array = array();
					if(isset($language_array['headline'])){
						$field_array['field_headline'] = array( 0 => $language_array['headline']);
					}
					if(isset($language_array['title'])){
						$field_array['title_field'] = array( 0 => $language_array['title']);
					}
					if(isset($language_array['description'])){
						$field_array['body'] = array( 0 => $language_array['description']);
					}
					//drupal_set_message('saving translation for: '.$assetid . ' for lang:' . $language_array['isocode'] . ' where orginal lang=' . $default_languge);
					_idsims_main_save_entity_translation('node', $node, $language_array['isocode'], $field_array, $default_languge);
				}
			}
		}
	} else {
		drupal_set_message('No language array for Asset ID: '.$assetid);
	}

	//drupal_set_message(print_r($field_data, TRUE));

	if($node_updated){
		node_save($node);
		//_idsims_set_created_updated_date($node);
	}
}

function _idsims_import_apply_organsation_ref(&$node, $field_ref, $object_id_arr){
	$field_ref = 'field_' . $field_ref;
	$cnt = 0;
	$node->{$field_ref}[LANGUAGE_NONE] = array();

	/* lookup organisation */
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
	->entityCondition('bundle', 'ids_organisation')
	->propertyCondition('status', NODE_PUBLISHED)
	->fieldCondition('field_object_id', 'value', $object_id_arr, 'IN')
	->addMetaData('account', user_load(1)); // Run the query as user 1.

	$result = $query->execute();

	if (!empty($result['node'])) {
		foreach($result['node'] as $organisation_nid => $organisation_node){
			$node->{$field_ref}[LANGUAGE_NONE][$cnt]['target_id'] = $organisation_nid;
			$node->{$field_ref}[LANGUAGE_NONE][$cnt]['entity'] = $organisation_node;
			$node->{$field_ref}[LANGUAGE_NONE][$cnt]['access'] = 1;
			$cnt++;
		}
	}
}

function _idsims_import_process_import_extras_update_node_subjects(&$node, $subjects, $assetid){
	if(isset($subjects['subject']['object_id'])){
		/* make single level array multivalue for consistency (and so loop below works) */
		$temp_array = array();
		$temp_array[0] = $subjects['subject'];
		$subjects = $temp_array;
	} else {
		$subjects = $subjects['subject'];
	}
	//drupal_set_message('::SUBJECTS=' . print_r($subjects, TRUE));
	foreach($subjects as $item){
		$cat_assetid = $item['object_id'];
		$cat_assetid_raw = substr($cat_assetid, 1);/*remove 'C' at front of asset ID */
		/*
		 * Process Content Partners /Funders
		 */
		$org_asset_id = _idsims_import_category_asset_id_to_organisation_asset_id_from_matrix($cat_assetid);
		if($org_asset_id){
			_idsims_import_apply_organsation_ref($node, 'content_partner_ref', array($org_asset_id));
		}
		
		/*
		 * Process Services
		 */
		$org_asset_id = _idsims_import_category_asset_id_to_organisation_asset_id_from_matrix($cat_assetid);
		if($org_asset_id){
			_idsims_import_apply_organsation_ref($node, 'service_ref', array($org_asset_id));
		}

		/*
		 * Process Flags
		 */
		if($cat_assetid_raw == IDSIMS_FLAG_ABSTRACT_SID){
			$node->field_full_abstract[LANGUAGE_NONE] = array(0 => array('value' => 1));
		}
		if($cat_assetid_raw == IDSIMS_FLAG_SENTINEL_OUTPUT_SID){
			$node->field_sentinel_output[LANGUAGE_NONE] = array(0 => array('value' => 1));
		}
		if($cat_assetid_raw == IDSIMS_FLAG_RECOMMENDED_READING_SID){
			$node->field_recommended_reading[LANGUAGE_NONE] = array(0 => array('value' => 1));
		}
	}
}

function _idsims_import_process_import_extras_update_node_sectors(&$node, $sectors, $assetid){
	if(isset($sectors['Sector']['object_id'])){
		/* make single level array multivalue for consistency (and so loop below works) */
		$temp_array = array();
		$temp_array[0] = $sectors['Sector'];
		$sectors = $temp_array;
	}
	drupal_set_message('::SECTORS=' . print_r($sectors, TRUE));
	foreach($sectors as $item){
		$cat_assetid = $item['object_id'];
		$cat_assetid_raw = substr($cat_assetid, 1);/*remove 'C' at front of asset ID */
		/*
		 * Process Updates (as a Collection)
		 */
		_idsims_import_updates_collection($node, $cat_assetid, $item['object_name']);

		/*
		 * Process BRIDGE Bibliography, Briefing or Report (and make them link to BRIDGE organisation)
		 */
		if(	$cat_assetid_raw == IDSIMS_BRIDGE_ORG_LINK_BIBLIO_SID ||
		$cat_assetid_raw == IDSIMS_BRIDGE_ORG_LINK_BRIEF_SID ||
		$cat_assetid_raw == IDSIMS_BRIDGE_ORG_LINK_REPORT_SID){
			_idsims_import_apply_organsation_ref($node, 'publishers', array(IDSIMS_BRIDGE_ORGANISATION_ID));
		}


		/*
		 * Process remaining Sectors as Document Types
		 */
		_idsims_import_sectors_to_doc_type($node, $cat_assetid, $cat_assetid_raw, $item['object_name']);

	}
}

/**
 * Process an asset for post processing data reorganisation
 */
function _idsims_import_process_import_post_process($nid, &$context) {
	$node = node_load($nid);
	$assetid = $node->field_object_id[LANGUAGE_NONE][0]['value'];
	_idsims_import_process_import_post_process_update_node($node, $context);
	$context['message'] = t('Updating node %title : Asset ID = %assetid', array('%title' => $node->title, '%assetid' => $assetid));
}

/**
 * Process the gterm reference fields of terms that have been moved to another vobaulary in Taxonomy Manager
 */
function _idsims_import_process_import_post_process_taxonomy_reference($nid, &$context) {
	$node = node_load($nid);
	$assetid = $node->field_object_id[LANGUAGE_NONE][0]['value'];
	_idsims_import_process_import_post_process_update_node_taxonomy_reference($node, $context);
	$context['message'] = t('Updating node %title : Asset ID = %assetid', array('%title' => $node->title, '%assetid' => $assetid));
}

/**
 * Process an asset for amalgamation of organisations
 */
function _idsims_import_process_import_amalgamate_orgs($nid, &$context) {
	$node = node_load($nid);
	if(isset($node->nid)){
		$assetid = $node->field_object_id[LANGUAGE_NONE][0]['value'];
		$node_updated = FALSE;
		/* is this an Eldis Org */
		if($node->field_site[LANGUAGE_NONE][0]['value'] == 'eldis'){
			/* then check if their is a BRIDGE version */
			$bridge_node = FALSE;
			
			$object_id_arr = array($assetid);
			/* lookup BRIDGE version by object_id */
			$query = new EntityFieldQuery();
			$query->entityCondition('entity_type', 'node')
			->entityCondition('bundle', 'ids_organisation')
			->propertyCondition('status', NODE_PUBLISHED)
			->fieldCondition('field_object_id', 'value', $object_id_arr, 'IN')
			->fieldCondition('field_site', 'value', 'bridge', '=')
			->addMetaData('account', user_load(1)); // Run the query as user 1.
		
			$result = $query->execute();
		
			if (!empty($result['node'])) {
				foreach($result['node'] as $organisation_nid => $organisation_node){
					/* should only be 1 max */
					$bridge_node = node_load($organisation_nid);
				}
			}		
			
			if($bridge_node){
				drupal_set_message('Found a BRIDGE organisation to copy. Asset ID='. $assetid . ' Title=' . $node->title);
				/* Copy the Description to the BRIDGE Description field */
				$field_language = _idsims_main_field_language('node', $bridge_node, 'body');
				$node->field_description_bridge[LANGUAGE_NONE][0]['value'] = $bridge_node->body[$field_language][0]['value'];
				$node->field_description_bridge[LANGUAGE_NONE][0]['format'] = 'full_html';
				/* Copy the BRIDGE theme/subject/region terms to the Eldis node */
				foreach($bridge_node->field_bridge_regions[LANGUAGE_NONE] as $delta => $term_obj){
					if(!isset($node->field_bridge_regions[LANGUAGE_NONE])){
						$node->field_bridge_regions[LANGUAGE_NONE] = array();
					}
					$node->field_bridge_regions[LANGUAGE_NONE][$delta] = $term_obj;
				}
				foreach($bridge_node->field_bridge_subjects[LANGUAGE_NONE] as $delta => $term_obj){
					if(!isset($node->field_bridge_subjects[LANGUAGE_NONE])){
						$node->field_bridge_subjects[LANGUAGE_NONE] = array();
					}
					$node->field_bridge_subjects[LANGUAGE_NONE][$delta] = $term_obj;
				}
				foreach($bridge_node->field_bridge_themes[LANGUAGE_NONE] as $delta => $term_obj){
					if(!isset($node->field_bridge_themes[LANGUAGE_NONE])){
						$node->field_bridge_themes[LANGUAGE_NONE] = array();
					}
					$node->field_bridge_themes[LANGUAGE_NONE][$delta] = $term_obj;
				}
				$node_updated = TRUE;
				/* delete BRIDGE oganisation node */
				node_delete($bridge_node->nid);
				drupal_set_message('Deleting NID:' . $bridge_node->nid);
			}
		}
		if($node_updated){
			node_save($node);
			_idsims_set_created_updated_date($node);
		}
		$context['message'] = t('Updating node %title : Asset ID = %assetid', array('%title' => $node->title, '%assetid' => $assetid));
	}
}


/*
 * When taxonomy terms are moved using Taxonomy Manager to another Vocab we need to update the term reference fields (this is for IDS Collections)
 */
function _idsims_import_process_import_post_process_update_node_taxonomy_reference(&$node, &$context) {
	/* Note just dealing with Subjects -> Collections, if you want to do other Vocabs have to add those */
	
	$node_updated = FALSE;
	
	$collection_terms = array();
	
	if(isset($node->field_eldis_subjects[LANGUAGE_NONE])){
		$new_order_refs = array();
		foreach($node->field_eldis_subjects[LANGUAGE_NONE] as $term_ref_id_obj) {
			$term_ref_tid = $term_ref_id_obj['tid'];
			$term_ref_term = taxonomy_term_load($term_ref_tid);
			$vid = $term_ref_term->vid;
			if($vid == IDSIMS_IDS_COLLECTIONS_VOC_ID){
				$collection_terms[] = $term_ref_tid;
			} else {
				$new_order_refs[] = $term_ref_id_obj;
			}
		}
		$node->field_eldis_subjects[LANGUAGE_NONE] = $new_order_refs;
	}	
	
	if(isset($node->field_bridge_subjects[LANGUAGE_NONE])){
		$new_order_refs = array();
		foreach($node->field_bridge_subjects[LANGUAGE_NONE] as $term_ref_id_obj) {
			$term_ref_tid = $term_ref_id_obj['tid'];
			$term_ref_term = taxonomy_term_load($term_ref_tid);
			$vid = $term_ref_term->vid;
			if($vid == IDSIMS_IDS_COLLECTIONS_VOC_ID){
				$collection_terms[] = $term_ref_tid;
			} else {
				$new_order_refs[] = $term_ref_id_obj;
			}
		}
		$node->field_bridge_subjects[LANGUAGE_NONE] = $new_order_refs;
	}
	
	if(count($collection_terms)){
		foreach($collection_terms as $collection_term) {
			$node->field_collections[LANGUAGE_NONE][] = array('tid' => $collection_term);
		}
		$node_updated = TRUE;
	}
	
	if($node_updated){
		drupal_set_message('Taxonomy reference moved to IDS Collections in node: ' . $node->title);
		node_save($node);
		_idsims_set_created_updated_date($node);
	}
}


function _idsims_import_process_import_post_process_update_node(&$node, &$context) {
	/*
	 * First check we haven't already run this process
	 */
	if(isset($node->field_build_pp_complete[LANGUAGE_NONE][0]['value'])){
		if($node->field_build_pp_complete[LANGUAGE_NONE][0]['value']){
			/* We have already run this, exit */
			return;
		}
		/* Set the flag so we don't run again */
		$node->field_build_pp_complete[LANGUAGE_NONE][0]['value'] = 1;
	}
	/*
	 * Create node references from asset IDs
	 *
	 * Publisher IDs from IDS API Module import to Publisher Node reference
	 */
	$node_updated = FALSE;

	if(isset($node->field_publisher_id[LANGUAGE_NONE])){

		$organisation_assetid_arr = array();
		foreach($node->field_publisher_id[LANGUAGE_NONE] as $publisher_id)
		{
			$organisation_assetid_arr[] = $publisher_id['value'];
		}

		_idsims_import_apply_organsation_ref($node, 'publishers', $organisation_assetid_arr);

		$node_updated = TRUE;
	}

	/*
	 * Update Site taxonomy reference from field_site
	 */
	if(isset($node->field_site[LANGUAGE_NONE][0]['value'])){
		if($node->field_site[LANGUAGE_NONE][0]['value'] == 'bridge'){
			$site_tid = IDSIMS_SITE_BRIDGE_TID;
		} else {
			$site_tid = IDSIMS_SITE_ELDIS_TID;
		}
		$node->field_site_ref[LANGUAGE_NONE] = array();
		$node->field_site_ref[LANGUAGE_NONE][0]['tid'] = $site_tid;

		$node_updated = TRUE;
	}


	/*
	 * Move external url field into new Document URL entity
	 */
	if(isset($node->field_external_urls[LANGUAGE_NONE])){
		/* there are some repeats in the URLs so let's ignore those by writting to and checking an array */
		$external_url_arr = array();
		/* get best guess language from the abstract language */
		$node_lang = 'English'; /* default to English */
		if(isset($node->field_language[LANGUAGE_NONE][0]['tid'])){
			$lang_term = taxonomy_term_load($node->field_language[LANGUAGE_NONE][0]['tid']);
			$node_lang = $lang_term->name;
		}
		$document_url_entity_id_arr = array();
		foreach($node->field_external_urls[LANGUAGE_NONE] as $external_url_obj){
			$external_url = $external_url_obj['value'];
			/* make sure not a duplicate */
			if(!in_array($external_url)){
				$entity_type = 'ids_document_url';
				$entity = entity_create($entity_type, array('type' => 'ids_document_url'));
				$entity_wrapper = entity_metadata_wrapper($entity_type, $entity);
				$entity_wrapper->field_document_url->set($external_url);
				if($language_term = taxonomy_get_term_by_name($node_lang, $vocabulary = 'ids_language')){
					$lang_tid = (isset($language_term->tid)) ? $language_term->tid:FALSE;
					if(is_array($language_term)){
						foreach($language_term as $language_term_item){
							$lang_tid = (isset($language_term_item->tid)) ? $language_term_item->tid:FALSE;
						}
					}
					if($lang_tid){
						$entity_wrapper->field_language_ref->set($lang_tid);
					}
				}
				$entity_wrapper->save();
				$entity_id_arr = entity_extract_ids($entity_type, $entity);
				$entity_id = $entity_id_arr[0];
				$document_url_entity_id_arr[$entity_id] = $entity;
			}
			$external_url_arr[] = $external_url;
		}
		$node->field_document_urls[LANGUAGE_NONE] = array();
		$cnt = 0;
		foreach($document_url_entity_id_arr as $eid => $entity){
			$node->field_document_urls[LANGUAGE_NONE][$cnt] = array();
			$node->field_document_urls[LANGUAGE_NONE][$cnt]['target_id'] = $eid;
			$node->field_document_urls[LANGUAGE_NONE][$cnt]['entity'] = $entity;
			$node->field_document_urls[LANGUAGE_NONE][$cnt]['access'] = 1;
			$cnt++;
		}
	}
	
	if($node_updated){
		node_save($node);
	}
	_idsims_set_created_updated_date($node);
}

/*
 * Set Date Updated/Created - straight to DB as wiht node_save updated date would be the save date/time
 */
function _idsims_set_created_updated_date($node){
	if(isset($node->field_date_updated[LANGUAGE_NONE][0]['value'])
	&& isset($node->field_date_created[LANGUAGE_NONE][0]['value'])){
		$updated_date_unix_timestamp = strtotime($node->field_date_updated[LANGUAGE_NONE][0]['value']);
		$created_date_unix_timestamp = strtotime($node->field_date_created[LANGUAGE_NONE][0]['value']);
		db_query('UPDATE {node} SET created=:created, changed=:changed WHERE nid=:nid', array(':created'=>$created_date_unix_timestamp,':changed'=>$updated_date_unix_timestamp,':nid'=>$node->nid));
	}	
}


function _idsims_import_simpleXML2array($xml)
{
	$array = json_decode(json_encode($xml), TRUE);
	return $array;
}

/**
 * Handle batch completion.
 */
function idsims_import_import_extras_orgs_finished($success, $results, $operations) {
	variable_set('idsims_import_batch_process_running', 0);
	$message = t('The organisation import extras has completed.');
	drupal_set_message($message);
	return $message;
}

/**
 * Handle batch completion.
 */
function idsims_import_import_term_extras_finished($success, $results, $operations) {
	variable_set('idsims_import_batch_process_running', 0);
	$message = t('The term extras import extras has completed.');
	drupal_set_message($message);
	return $message;
}

/**
 * Handle batch completion.
 */
function idsims_import_import_extras_api_finished($success, $results, $operations) {
	variable_set('idsims_import_batch_process_running', 0);
	$message = t('The organisation import extras from API has completed.');
	drupal_set_message($message);
	return $message;
}

/**
 * Handle batch completion.
 */
function idsims_import_import_extras_finished($success, $results, $operations) {
	variable_set('idsims_import_batch_process_running', 0);
	$message = t('The import extras has completed.');
	drupal_set_message($message);
	return $message;
}

/**
 * Handle batch completion.
 */
function idsims_import_import_post_process_finished($success, $results, $operations) {
	variable_set('idsims_import_batch_process_running', 0);
	$message = t('The import post process has completed.');
	drupal_set_message($message);
	return $message;
}

/**
 * Handle batch completion.
 */
function idsims_import_import_post_process_taxonomy_reference_finished($success, $results, $operations) {
	variable_set('idsims_import_batch_process_running', 0);
	$message = t('The taxonomy reference update has completed.');
	drupal_set_message($message);
	return $message;
}

function idsims_import_get_endpoint_response($endpoint_url){
	if (($response_xml_data = file_get_contents($endpoint_url))===false){
		drupal_set_message("Error fetching XML" . $endpoint_url);
	} else {
		libxml_use_internal_errors(true);
		$data = simplexml_load_string($response_xml_data);
		if (!$data) {
			drupal_set_message("Error loading XML" . $endpoint_url);
			foreach(libxml_get_errors() as $error) {
				drupal_set_message("libxml_get_error:: " . $error->message);
			}
		} else {
			return $data;
		}
	}
	return false;
}


/* 
 * Country CSV import thing - only need to run once!
*/


/**
 * Build a form to upload CSV to.
 */
function idsims_import_country_regions_form() {
	$form['#attributes'] = array(
    'enctype' => 'multipart/form-data'
    );
    $form['csvfile'] = array(
    '#title' => t('CSV File'),
    '#type'  => 'file',
    '#description' => ($max_size = parse_size(ini_get('upload_max_filesize'))) ? t('Due to server restrictions, the <strong>maximum upload file size is !max_size</strong>. Files that exceed this size will be disregarded.', array('!max_size' => format_size($max_size))) : '',    
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Commence Import'),
    );
    $form['#validate'] = array(
    'idsims_import_country_regions_validate_fileupload',
    );
    return $form ;
}

/**
 * Handle form submission. Read the CSV into a set of batch operations
 * and fire them off.
 */
function idsims_import_country_regions_form_submit(&$form, &$form_state) {
	$batch = array(
    'title' => t('Importing CSV ...'),
    'operations' => array(),
    'init_message' => t('Commencing'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('An error occurred during processing'),
    'finished' => 'idsims_import_country_regions_form_finished',
	) ;

	if ( isset( $form_state['values']['csvupload'] ) ) {
		if ( $handle = fopen($form_state['values']['csvupload'], 'r') ) {
			$line_count = 1 ;
			$first = TRUE ;
			$line = fgetcsv($handle, 4096);
			while ( $line = fgetcsv($handle, 4096) ) {
				/**
				 * we use base64_encode to ensure we don't overload the batch
				 * processor by stuffing complex objects into it
				 */
				
				$data = new stdClass();
				$country_asset_id = trim($line[0]);
				$region_object_id = trim($line[1]);
				if($region_object_id && $country_asset_id){
					$data->country_asset_id = $country_asset_id;
					$data->region_object_id = $region_object_id;
					$batch['operations'][] = array('_idsims_import_process_country_regions', array($data)); 
				}
					
			}
			fclose($handle);
		} // we caught this in csvimport_form_validate()
	} // we caught this in csvimport_form_validate()

	batch_set($batch);
}


/**
 * Handle batch completion.
 */
function idsims_import_country_regions_form_finished($success, $results, $operations) {
	variable_set('idsims_import_batch_process_running', 0);
	$message = t('The country to region import extras has completed.');
	drupal_set_message($message);
	return $message;
}


/**
 * Validate the file upload. It must be a CSV, and we must
 * successfully save it to our import directory.
 */
function idsims_import_country_regions_validate_fileupload(&$form, &$form_state) {
	$validators = array(
    'file_validate_extensions' => array( 'csv CSV' ),
	) ;
	if ( $file = file_save_upload('csvfile', $validators, 'temporary://') ) {
		// The file was saved using file_save_upload() and was added to
		// the files table as a temporary file. We'll make a copy and let
		// the garbage collector delete the original upload.
		$csv_dir = 'temporary://csvfile';
		$directory_exists = file_prepare_directory($csv_dir, FILE_CREATE_DIRECTORY);
		if ($directory_exists) {
			$destination = $csv_dir .'/' . $file->filename;
			if (file_copy($file, $destination, FILE_EXISTS_REPLACE)) {
				$form_state['values']['csvupload'] = $destination;
			}
			else {
				form_set_error('idsims_import', t('Unable to copy upload file to !dest', array('!dest' => $destination)));
			}
		}
	}
}


/**
 * Process an asset for extra fields import oganisations
 */
function _idsims_import_process_country_regions($data, &$context) {

	/* Lookup region */
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'taxonomy_term')
	->entityCondition('bundle', 'ids_eldis_regions')
	->fieldCondition('field_object_id', 'value', $data->region_object_id, '=')
	->addMetaData('account', user_load(1)); // Run the query as user 1.

	$result = $query->execute();
	
	if (!empty($result['taxonomy_term'])) {
		foreach($result['taxonomy_term'] as $region_tid => $region_term){
			$region_term_full = taxonomy_term_load($region_tid);
		}
	}
	
	/* Lookup country */
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'taxonomy_term')
	->entityCondition('bundle', 'ids_countries')
	->fieldCondition('field_object_id', 'value', 'A' . $data->country_asset_id, '=')
	->addMetaData('account', user_load(1)); // Run the query as user 1.

	$result = $query->execute();
	
	if (!empty($result['taxonomy_term'])) {
		foreach($result['taxonomy_term'] as $country_tid => $country_term){
			$country_term_full = taxonomy_term_load($country_tid);
		}
	}
	
	$country_term_full->field_region_eldis[LANGUAGE_NONE] = array();
	$country_term_full->field_region_eldis[LANGUAGE_NONE][0]['tid'] = $region_term_full->tid;
	
	taxonomy_term_save($country_term_full);
	
	$context['message'] = t('Updating country %title with Region = %region', array('%title' => $country_term_full->name, 'region' => $region_term_full->name));
}



